(in-ns 'test.run)

(require '[test-compile.test2-eval :as test2])
(require '[test-compile.test3-env :as test3])
(require '[test-compile.test4 :as test4])
;; ;; (require '[test-compile.test5-tco :as test6])
(require '[test-compile.test6-file :as test6])
(require '[test-compile.test7 :as test7])
(require '[test-compile.test8 :as test8])

(defn run-tests []
  (test2/test)
  (test3/test)
  (test4/test4a)
  (test4/test4b)
  (test4/test4c)
  (test4/test4d)
  (test4/test4e)
  ;; ;; (test5/test)
  (test6/test)
  (test7/test7a)
  ;; ;; (test7/test7b)
  (test7/test7c)
  (test8/test)

  )
